---
language: python
python: "3.8"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Install role dependencies
  - ansible-galaxy install -r requirements.yml

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
