---
- import_tasks: dropbear.yml
  when: >
    ssh_public_key is defined
    or ssh_port is defined

- import_tasks: wireless.yml
  when: >
    ssid is defined
    or key is defined
    or encryption is defined
    or channel is defined

- import_tasks: network.yml
  when: >
    ipaddr is defined
    or netmask is defined
