---
- include_tasks: system.yml
  when: zonename is defined

- name: Include tasks for dropbear
  include_tasks: dropbear.yml
  when: >
    ssh_public_key is defined
    or ssh_port is defined

- import_tasks: passwd.yml
  when: passwd is defined

- block:
  - name: Include tasks for wireless 1
    include_tasks: wireless.yml
    vars:
      wifi_index: 1
  always:
  - name: Include tasks for wireless 0
    include_tasks: wireless.yml
    vars:
      wifi_index: 0
  when: >
    ssid is defined
    or key is defined
    or encryption is defined
    or channel is defined

- name: Include tasks for networking
  include_tasks: network.yml
  when: >
    ipaddr is defined
    or netmask is defined
    or ipv6_disabled is defined
