# https://openwrt.org/docs/guide-user/network/wifi/basic

- name: Configure Wi-Fi SSID
  uci:
    command: set
    key: wireless.@wifi-iface[{{ wifi_index }}]
    value:
      ssid: "{{ ssid }}"
  when: ssid is defined
  notify:
  - uci commit
  - wifi reload

- name: Configure Wi-Fi Key
  uci:
    command: set
    key: wireless.@wifi-iface[{{ wifi_index }}]
    value:
      key: "{{ key }}"
  when: key is defined
  notify:
  - uci commit
  - wifi reload

- name: Configure Wi-Fi Encryption
  uci:
    command: set
    key: wireless.@wifi-iface[{{ wifi_index }}]
    value:
      encryption: "{{ encryption | default('psk2', true) }}"
  when: >
    encryption is defined
    or key is defined
  notify:
  - uci commit
  - wifi reload

- name: Configure Wi-Fi Channel
  uci:
    command: set
    key: wireless.@wifi-device[{{ wifi_index }}]
    value:
      channel: "{{ channel }}"
  when: channel is defined
  notify:
  - uci commit
  - wifi reload

- name: Enable Wi-Fi
  uci:
    command: set
    key: wireless.@wifi-device[{{ wifi_index }}]
    value:
      disabled: '0'
  notify:
  - uci commit
  - wifi reload
