---
- name: uci commit
  uci:
    command: commit

- name: system reload
  service:
    name: system
    state: reloaded

- name: dropbear restart
  service:
    name: dropbear
    state: restarted

- name: wifi reload
  command: wifi

- name: network reload
  service:
    name: network
    state: reloaded
